### ISSUE TITLE
File Input and Editing

### ISSUE THREAD

**Issue by jjacobsonn** [alex0112/abacus#100]
- Modify the application to support loading a file into the GUI, allowing the user to view, inspect, and edit function commands and their order before execution.
- Ensure the GUI supports the following actions:
   - Viewing the file contents.
   - Adding new function codes and data values.
   - Modifying existing function codes and data values.
   - Deleting function codes and data values.
   - Performing cut, copy, and paste actions.
- Handle situations where user actions may exceed the maximum data size (100 entries covering registers #00 - #99).

**Comment by Kainny2000** [comment]
Code implemented with some gub added on the TODO for milestone 5
