### ISSUE TITLE
UVsim adaptation to 6-digit values

### ISSUE THREAD

**Issue by Kainny2000** [alex0112/abacus#119]
Expand the scope of your application so data files can contain 250 lines instead of 100 (and likewise your internal memory registers will now go from 000 to 249 to match).  Note that this change will require the support of three-digit memory addresses instead of two -- as a result this feature will create a "new" file format supported from this time forward that will contain six digit words instead of four.
*Some additional notes: 
-You should not support more than 250 lines (even though the address space now supports up to 1000 lines in theory).  Any command that references a line # that's not between 000 and 249 will be judged invalid.  Make sure your application does not allow the loading or editing of a file to have more than 250 lines.
-Since your new word size is six digits, make sure your application can handle six digit math operations correctly, with the same proper overflow handling that you did with four digits.  
-The function codes for each operation will not change: simply append a zero to the beginning of each functional code (i.e. 010 instead of 10 will represent a READ command here using this 6 digit format).

*Some important notes:
When converting files from 4-digits to 6, remember that a line in a file can be either a functional code (like 1007 - READ to memory address 07) or a numerical value (5555 which represents the number five thousand five hundred fifty five).  This will matter when you are considering how to convert, because the first example should be converted to 010007 (function code is still 010, target address is still 007) while the second example is converted to 005555 (not 055055) since it needs to represent the same raw number value.  What happens if the file has the raw number 1007 (intended to mean one thousand and seven)?  How does your conversion algorithm know whether it is supposed to be a READ command or a number?  For this milestone, to simplify this confusion, we will be making a restriction that raw number values in test files will NOT use valid function codes for the first two digits.  That way if you encounter a number in your conversion algorithm, if the first two digits are a valid function code, treat it as a function code (and convert it using 0XX0XX formatting), and if it is not, treat it as a number (convert using 00XXXX formatting).  Obviously, this confusion would be something you'd have to address in real life (if this were a real application), but in this context, that level of complexity is beyond the scope of this project, so we will simplify it for this project to make your conversion algorithms much simpler to implement.

**Comment by alex0112** [comment]
Started work on this in PR #132

**Comment by alex0112** [comment]
Tasks:
- [x] data files can contain 250 lines instead of 100
  - [x] unit tests
- [x] Memory addressing format can now be from 000 249
  - [x] unit tests
- [x] modify word size to include 6 digits
  - [x] unit tests
- [x] overflow handled with 6 digits
  - [x] unit tests

**Comment by alex0112** [comment]
Should be working :crossed_fingers:

**Comment by alex0112** [comment]
Completed in #132
