### ISSUE TITLE
TODO Fix branching issues, test 2 and test 4 still don’t pass.

### ISSUE THREAD

**Issue by Kainny2000** [alex0112/abacus#123]
TODO feedback:  "Branching is still an issue, both test files (test2/test4) that involve branching don't work properly.  The math files do work, including overflow management, so good job fixing that up. "

**Comment by alex0112** [comment]
I am not sure how the professor wishes this to work. I have emailed them about this.

**Comment by alex0112** [comment]
wontfix until we have more information
